#######################
##__GLOBAL_SETTINGS__##
#######################

deploy_type: deployment #deployment, daemonset, statefulset or false if not needed
  configmaps: false
  secrets:  false
  services: false
  ingress: false
  pvc: false
  job: false
  cronjob: false
  hpa: false

##__IMAGE PULL SECRET: default is the application name {{ template "app.fullname" . }}}-pullsecret
## https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecret: ""

##__VOLUMES
## https://kubernetes.io/docs/concepts/storage/
volumes: {}

##__SECURITY CONTEXT FOR A PODS
## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext: {}

##__DEFAULT podAnnotations empty
## https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

##__DON'T USE ROLLME IN ARGOCD
## https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
rollme:
  enabled: false

##__NUMBER OF REPLICA POD default 1 if empty
replicaCount: ""

##__SETTINGS ONLY FOR STATEFULSET
##__POD MANAGEMENT POLICY only for StatefulSet, default OrderedReady if empty
## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
podManagementPolicy: {}
#OrderedReady or Parallel
serviceName: ""

##__SERVICE ACCOUNT FOR POD
## https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccountName: ""

##__TOLERATIONS for pods assignment
## https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

##__POD UPDATE STRATEGY default RollingUpdate 25%/25%
updateStrategy: {}

##__AFFINITY RULES 
## https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity: {}


##################
##__DEBUG_MODE__##
##################
debug_mode:
  enabled: false
  command: ["sleep"]
  args: ["infinity"]


##################
##__CONTAINERS__##
##################
containers: {}


######################
##__INITCONTAINERS__##
######################
initcontainers: {}


################
##__SERVICES__##
################
services: {}


###############
##__INGRESS__##
###############
ingress: {}


##################
##__CONFIGMAPS__##
##################
configmaps: {}


###############
##__SECRETS__##
###############
secrets: {}


###############################
##__PERSISTENT_VOLUME_CLAIM__##
###############################
persistentVolumeClaim: {}


##################################
##__HORIZONTAL_POD_AUTOSCALING__##
##################################
autoscaling: {}


############
##__JOBS__##
############
job: {}


################
##__CRONJOBS__##
################
cronjob: {}