{{- if and (eq .Values.global_settings.ingress true) (.Values.ingress) }}
{{- range $k, $v := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $k }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations: {{- include "values.render" (dict "value" .annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .host }}
  - host: {{ .name }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}
      {{- end }}
    {{- end }} 
  tls:
  - hosts:
    {{- range .host }}
    {{- if .tls.enabled }}
    - {{ .name }}
    {{- end }}
    {{- end }}
---
{{ end }}
{{ end }}