{{- if .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret }}
type: kubernetes.io/dockerconfigjson
---
{{- end -}}