{{- if and (eq .Values.global_settings.pvc true) (.Values.persistentVolumeClaim) (ne .Values.global_settings.deploy_type "statefulset")}}
{{- range $k, $v := .Values.persistentVolumeClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $k }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations: {{- include "values.render" (dict "value" .annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .storageCapasity }}
  storageClassName: {{ .storageClassName }}

---
{{ end }}
{{ end }}