{{- if and (eq .Values.global_settings.secrets true) (.Values.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" $ }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := .Values.secrets }}
    {{ $k }}: {{ $v | b64enc | quote }}
  {{- end}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" $ }}-external
  labels:
    {{- include "app.labels" $ | nindent 4 }}
data:
{{- range $path, $_ :=  .Files.Glob  "secrets/*" }}
{{- if ne (base $path) "README.md" }}
{{- $v := $.Files.Get $path | fromYaml }}
{{- range $key, $val := $v }}
{{ $key | indent 2 }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
{{- end }}
---
{{- end -}}